filter:
    excluded_paths:
        - tests/*

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        php:
            version: 8.0

    nodes:
        tests-with-coverage:
            tests:
                override:
                    - command: ./vendor/bin/phpunit --coverage-clover=clover.xml
                      coverage:
                          file: clover.xml
                          format: clover
